Algoritmo "Apostila EX002"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/08/2022
Var
// Seção de Declarações das variáveis 
nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("What's your name? ")
Leia(nome)
EscrevaL("Hello ",nome,", Nice to meet you!")

Fimalgoritmo