Algoritmo "Exercicio 01 Aula 06"
Var
// Seção de Declarações das variáveis 
   ano_nascimento, ano_atual, idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite o ano atual: ")
   Leia(ano_atual)
   Escreva("Digite o ano de nascimento: ")
   Leia(ano_nascimento)
   idade <- ano_atual - ano_nascimento
   EscrevaL("Sua idade é",idade," anos")
   
Fimalgoritmo
